# Generated by Django 5.1.7 on 2025-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
