# Generated by Django 5.1.7 on 2025-07-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_certificado_ativo_projeto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
